# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
